#!/usr/bin/env ruby

load File.expand_path('../split-gpg2.rb', __FILE__)

s = SplitGPG2::Server.new $stdin, $stdout, ENV['QREXEC_REMOTE_DOMAIN']

debug_log = ENV['QUBES_SPLIT_GPG2_DEBUG_LOG']
if debug_log
  s.log = File.open debug_log, 'a'
  s.log.sync = true
end

timer_names = {
  'QUBES_SPLIT_GPG2_PKSIGN_AUTOACCEPT_TIME' => :PKSIGN,
  'QUBES_SPLIT_GPG2_PKDECRYPT_AUTOACCEPT_TIME' => :PKDECRYPT
}
timer_names.each do |name, key|
  env = ENV['name']
  if /\A\d+\z/ =~ env
    s.timer_delay[key] = env.to_i
  else
    s.timer_delay[key] = nil
  end
end

s.run
