#!/bin/bash

. ~user/.split-gpg2-rc

agent_socket=`gpgconf --list-dirs | grep '^agent-socket:' | cut -d ':' -f 2`

gpgconf --kill gpg-agent &>/dev/null

socat "unix-listen:$agent_socket,fork,unlink-early" "exec:qrexec-client-vm $SPLIT_GPG2_SERVER_DOMAIN qubes.Gpg2"
