#!/bin/bash

agent_socket=`gpgconf --list-dirs | grep '^agent-socket:' | cut -d ':' -f 2`

agent_pid=`lsof -F p "$agent_socket" | cut -b 2-`

if [ -n $agent_pid ]; then
        kill $agent_pid
fi

rm -f "$agent_socket"

socat "UNIX-LISTEN:$agent_socket,fork" EXEC:/usr/share/split-gpg2/split-gpg2-client-wrapper
