#!/bin/bash

. ~user/.split-gpg2-rc

socat="`type -p socat`"

tmp_dir="`mktemp -d --tmpdir split-gpg.XXXXXXXXXX`"
socket="$tmp_dir/socket"

/usr/lib/qubes/qrexec-client-vm $QUBES_GPG_DOMAIN qubes.Gpg2 "$socat" "UNIX-LISTEN:$socket" - &

while [ ! -S "$socket" ]; do
        sleep 0.01
done

socat "UNIX-CONNECT:$socket" -
