#!/bin/bash

for d in /etc "${XDG_CONFIG_HOME:-$HOME/.config}"; do
    rc_file="$d/split-gpg2-rc"
    if [ -r "$rc_file" ]; then
        . "$rc_file"
    fi
done

if [ -z "$SPLIT_GPG2_SERVER_DOMAIN" ]; then
    SPLIT_GPG2_SERVER_DOMAIN="@default"
fi

agent_socket=`gpgconf --list-dirs | grep '^agent-socket:' | cut -d ':' -f 2`

gpgconf --kill gpg-agent &>/dev/null

socat "unix-listen:$agent_socket,fork,unlink-early" "exec:qrexec-client-vm $SPLIT_GPG2_SERVER_DOMAIN qubes.Gpg2"
